import Home from "./Home";
import Register from "./Register";
import Login from "./Login";
import ForgotPassword from "./ForgotPassword";
import PlanSubscription from "./PlanSubscription";
import Error from "./Error";
import About from "./About";
import Exercise from "./Exercise";
import ExerciseDetail from "./ExerciseDetail";
import PlanDetail from "./User/PlanDetail";
import Profile from "./Profile";
import UserDashBoard from "./User/UserDashBoard";
import FavouriteExercises from "./User/FavouriteExercises";
import AdminDashBoard from "./Admin/AdminDashBoard";
import SubscriberList from "./Admin/SubscriberList";
import CreatePlan from "./Admin/CreatePlan";
import Plans from "./Admin/Plans";
import UpdatePlan from "./Admin/UpdatePlan";
import UserList from "./Admin/UserList";
import PlanDetails from "./PlanDetails";
import PlanFullDetail from "./User/PlanFullDetail";
import ContactUs from "./Admin/ContactUs";
import TrainerDetails from "./TrainerDetails";
import Feedback from "./Feedback";
import Feedbacks from "./User/Feedbacks";
import FeedbackList from "./Admin/FeedbackList";
// import PlanFullDetail from "./User/PlanFullDetail";
export {Home, Register, Login, ForgotPassword, PlanSubscription, Error, About, Exercise, ExerciseDetail, PlanDetail, Profile, UserDashBoard, FavouriteExercises, AdminDashBoard, SubscriberList, CreatePlan, Plans, UpdatePlan, UserList, PlanDetails, PlanFullDetail, ContactUs, TrainerDetails, Feedback, Feedbacks, FeedbackList };